### ISSUE TITLE
Error: EEXIST: File exists

### ISSUE THREAD

**Issue by fyrak1s** [cshuaimin/scd#3]
I am unable to start the program on my Arch system:
```
$ scd
Error: EEXIST: File exists
```

Doing
```
scd fish-init | source
```
gives no output. I am also not able to abort the application with `q` or `CTRL+C`

EDIT: Similar issue: https://www.reddit.com/r/rust/comments/gasc1f/i_wrote_a_file_manager_that_syncs_its_current/fp2fuv4/

**Comment by mastern2k3** [comment]
bump, this happens for me too.

**Comment by cshuaimin** [comment]
```bash
rm /tmp/{scd-cmds-to-run,scd-shell-events}
```

It try to create these two FIFOs, but it exists. These two files are used to communicate to the shell, and should be deleted when exiting. However if program crashes, these files are kept and preventing next start.

**Comment by fyrak1s** [comment]
@cshuaimin The fix is not on crates.io is it?

Tried to update using `cargo install scd` but the issue is still present.

**Comment by cshuaimin** [comment]
Yes.

There are still some bugs, when get fixed, I will update to crates.io.

**Comment by cshuaimin** [comment]
@Nuc1eoN `0.1.1` published to crates.io now!
